# Site settings
title: Tahmid ↗ Blogs
header-img: img/home-bg.jpg
email: tahmidefaz@gmail.com
copyright_name: Tahmid Efaz
description: "This is my personal blog page - Tahmid Efaz"
baseurl:
url: ""
instagram_username: tahmidefaz
github_username:  tahmidefaz
linkedin_username: tahmid-efaz
email_username:  tahmidefaz@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-75111731-3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
